### PR TITLE
Correctly encode high code points in XML

### PR DESCRIPTION
**Pull request by sabberworm**
Code points beyond the BMP were written as XML-escaped surrogate pairs (which is illegal XML) instead of a single code point entity. This PR fixes that.

### CODE REVIEW

**Comment by sabberworm** [comment]
Regarding the failing unit tests: I’ve had those with the current master branch as well. They seem to be floating point precision issues.

**Comment by nfroidure** [comment]
The build probably fails since the last SVGPathData patch due to a bug fix. I'll have a look at it and merge.

**Comment by sabberworm** [comment]
Maybe we can do away with escaping this value altogether. The generated file is utf-8 anyway, why not just use that and only encode `<`, `>` and `&`?

**Comment by nfroidure** [comment]
In fact, i just made the SVG font template on an online example basis and i dumbly kept its formatting. I don't know which impact it could have to leave unicode chars as is instead of encoding them.

**Comment by sabberworm** [comment]
So I’ve fixed the pull request by changing what’s expected. Also regarding if we need escaping at all: I would leave it as-is now. It might be more readable if not everything is escaped but it can’t hurt…

**Comment by sabberworm** [comment]
Somehow I can’t get the `node-expat` dependency to install on travis in all newer node versions even though it works fine on my local machine with node v4.1.2. Should I try to find a different XML parser to validate the tests with? Or should I try not using an XML parser at all?

**Comment by nfroidure** [comment]
That's what i did for the other tests, i think it is strong enough and simpler to manage expected output in separated files.

**Comment by sabberworm** [comment]
Yes but it’s also fallible. If we did do the change wherein we’d only escape some characters but not all, all of the expected output files would have to change… But I’m doing it like this now. I don’t see any other simple fix.

**Comment by nfroidure** [comment]
I agree, but the path is shorter ;). Thanks for your contribution.

**Pull request merged**
