### PR TITLE
Add color property to glyph object

### PR DESCRIPTION
**Pull request by TylerYang**
Map attribute 'fill' to color property

### CODE REVIEW

**Comment by nfroidure** [comment]
Unfortunately the fill property is a <paint> value http://www.w3.org/TR/SVG/painting.html#SpecifyingPaint

It means it is a bit complexer than just specifying a color. You should at least test if the attribute value is a color and then fill it only if it match. You also could pick parent fill value if the inherit value is found (see this function that does a similar job https://github.com/nfroidure/svgicons2svgfont/blob/a28c981bfff2dc49f999a358f52728beea09bae0/src/index.js#L43 )

**Comment by TylerYang** [comment]
That make sense, I will PR a new one later.

Here is my question,
 What if there are *more than one fill attribute* in svg element and their value are *different*? 

For example, 
```svg
<svg>
    <g> 
        <path fill="#F00"  d="M4.." />
    </g>
    <path fill="#CCC" />
</svg>
```
In this case, I will simply set the *last color attribute*(If it inherits from its parent, then set the parent's val)  to `glyph`.

**Comment by TylerYang** [comment]
Hi @nfroidure , do you accept with this PR? Because this is really important for my project. Any comments are welcome. Thx.

**Comment by nfroidure** [comment]
Just looked at your PR but it comes with no test at all. Can't merge without at least one test.

**Comment by TylerYang** [comment]
My bad, I will submit the test case tomorrow. Thx...

**Comment by TylerYang** [comment]
@nfroidure  Hi, just added some test cases. Looking forward to your advise. Thx.

**Comment by TylerYang** [comment]
Hi @nfroidure , is there anything I can do to improve this functionality so that you will accept this PR?

**Comment by nfroidure** [comment]
@TylerYang sorry for the elapsed time, couldn't review your work yet. I'll look at it this week.

**Comment by TylerYang** [comment]
@nfroidure  It's OK, I will be waiting.

**Comment by TylerYang** [comment]
https://github.com/nfroidure/gulp-svgicons2svgfont/pull/31  Can you review this PR also?  It failed to pass the tests because in preview `svgicons2svgfont` module, it didn't have the `color` property.

**Comment by nfroidure** [comment]
You can easily make it pass by using your repo's url. I'll try to review it asap anyway.

**Comment by TylerYang** [comment]
@nfroidure  I would like to do it so, but seems in China, I cannot access to this url at this moment. All I can get is `ERR:TIMEOUT` from their CDN.

**Pull request merged**
