### PR TITLE
Support Unicode characters with higher codepoint

### PR DESCRIPTION
**Pull request by teohhanhui**
... (outside of Basic Multilingual Plane)

Use String.fromCodePoint (with polyfill) instead of String.fromCharCode
Use String.codePointAt (with polyfill) where appropriate instead of String.charCodeAt

### CODE REVIEW

**Comment by nfroidure** [comment]
Thanks for the PR.

Would be nice to add its little browser here https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js#L31 ;)

Also a test with some concerned codepoints would be nice to have.

**Comment by teohhanhui** [comment]
> Would be nice to add its little browser here https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js#L31 ;)

Sorry, I don't get what you mean...

**Comment by teohhanhui** [comment]
Cover more bases, and test added.

**Comment by nfroidure** [comment]
Clean. Thanks for the PR!

**Pull request merged**
